const mongoose = require('mongoose');
const { Schema } = mongoose;

const drugSchema = new Schema({
  tradeName: String,
  labelName: String,
  genericName: String,
  cin: String,
  ndc: String,
  upc: {
    type: String,
    unique: true,
  },
  strength: String,
  form: String,
  packageQty: String,
  packageSize: String,
  unit: String,
  cardinalContract: String,
  cardinalStockStatus: String,
  cardinalQtyAvailable: String,
  cardinalCost: String,
  cardinalRetailPriceChanged: String,
  mfr: String,
  dist: String,
  productType: String,
  deaSchedule: String,
  abRating: String,
  returnPackaging: String,
  specialty: String,
  altCIN: [String],
  altNDC: [String],
  altTradeName: [String],
  altStrength: [String],
  altForm: [String],
  altSize: [String],
  altType: [String],
  altCost: [String],
  altContract: [String],
  cardinalHistOrderDate: [String],
  cardinalHistInvoiceDate: [String],
  cardinalHistOrderQty: [String],
  cardinalHistShipQty: [String],
  cardinalHistUnitCost: [String],
  cardinalHistTotalCost: [String],
  cardinalHistInvoiceNum: [String],
  cardinalHistOrderMethod: [String],
  cardinalWACEffectiveDate: [String],
  cardinalWAC: [String],
  cardinalWACPercentChange: [String],
  dateLastUpdatedCardinal: Date,
  dateLastUpdatedSmartSource: Date,
  isGeneric: Boolean,
  lastDateCardinalPriceMatched: Date,
  ourPricePerUnit: Number,
  ourBatchQty: [Number],
  ourBatchPrice: [Number],
  // KeySource Data
  keySourceDesc: String,
  keySourceCost: String,
  keySourceStock: String,
  keySourceExp: String,
  keySourceAltDesc: [String],
  keySourceAltCost: [String],
  keySourceAltStock: [String],
  keySourceAltExp: [String],
  dateLastUpdatedKeySource: Date,
  // SmartSource Data
  smartSourceName: String,
  smartSourceCost: String,
  smartSourcePerDose: String,
  smartSourcePerDose: String,
  smartSourceAltName: [String],
  smartSourceAltNDC: [String],
  smartSourceAltCost: [String],
  smartSourceAltPerDose: [String],
});

module.exports = mongoose.model('Drug', drugSchema);
